### ISSUE TITLE
No license in the repository

### ISSUE THREAD

**Issue by ljli** [ThoreKr/keycloak-last-login-event-listener#7]
There doesn't seem to be a license in the repository. Would it be possible to add one? GitHub can help with it a bit: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository.

**Comment by ThoreKr** [comment]
I have considered this in the past, but found 3 issues, which make licensing rather difficult:

1. The base work for this repo is https://github.com/zonaut/keycloak-extensions - which has no license.
2. There have been other contributors, who'd basically have to agree as well
3. I question the threshold of originality. This is basically the example code and a two line marble added to the mix.

More of a sidenote - I published the code because it was a recurring question in various places with the intention for others to be able to adapt it to their needs, similarly to zonauts repo. Not necessarily to directly run it.

**Comment by ljli** [comment]
Thanks for considering. The reasoning is understandable, I was wondering about some of these points as well. Feel free to close the ticket.
