### ISSUE TITLE
Doesn't persist attributes in KC 20.0.2

### ISSUE THREAD

**Issue by xgp** [ThoreKr/keycloak-last-login-event-listener#8]
Thanks for the great extension. I have used it in previous versions, but I have just noticed that when using it in KC 20.0.2, the user attributes are no longer persisted. I suspect this is more of a Keycloak change than something that changed here, but I wanted to report that it no longer works here.

**Comment by ThoreKr** [comment]
Thanks for the report.
Unfortunately i can't reproduce the issue.
I'm nut running this exact version of the code, but the functional part is identical. Only thing different to the version in the repository were the remainder of the jboss deployment structure and the pinned dependency version of the keycloak libraries.

Are you manually setting these before building?
Otherwise there is an update in the upgrade-20 branch, which also moves to Java 17, to align with future keycloak releases.

**Comment by xgp** [comment]
Hi @ThoreKr I made a very simple test, and ran it in KC 20.0.2

This doesn't persist the attribute:
```java
  public void onEvent(final Event event) {
    if (EventType.LOGIN.equals(event.getType())) {
      UserModel u = session.users().getUserById(realm, event.getUserId());
      u.setSingleAttribute("foo", "bar");
    }
  }
```

This works:
```java
  public void onEvent(final Event event) {
    if (EventType.LOGIN.equals(event.getType())) {
      KeycloakModelUtils.runJobInTransaction(session.getKeycloakSessionFactory(), s -> {
        UserModel u = s.users().getUserById(realm, event.getUserId());
        u.setSingleAttribute("foo", "bar");
      });
    }
  }
```

I'll put together a sample repo and submit a keycloak issue. This isn't unique to your extension.
